#
# The API uses transparent HTTPS to be called over HTTPS, and to call other components
# The API also uses explicit HTTPS to connect to the Postgres database
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demoapi
---
kind: Service
apiVersion: v1
metadata:
  name: demoapi-svc
  annotations:
    ingress.kubernetes.io/service-upstream: 'true'
spec:
  selector:
    app: demoapi
  ports:
  - name: http
    protocol: "TCP"
    port: 8000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demoapi
  labels:
    app: demoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapi
  template:
    metadata:
      labels:
        app: demoapi
        sidecar.istio.io/inject: 'true'
        spire-managed-dns-identity: 'true'
        dnsIdentity: demoapi
      annotations:
        inject.istio.io/templates: 'sidecar,spire'
    spec:
      serviceAccountName: demoapi
      containers:
      - name: demoapi
        image: demoapi:v1
        env:
          - name: API_PORT
            value: '8000'
          - name: API_DB_CONNECTION
            value: 'jdbc:postgresql://dbserver-svc/products?sslmode=verify-full&sslfactory=io.spiffe.provider.SpiffeSslSocketFactory'
          - name: SPIFFE_ENDPOINT_SOCKET
            value: 'unix:///spiffe-workload-api/socket'
        volumeMounts:
          - name: spiffe-workload-api
            mountPath: /spiffe-workload-api
            readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demoapi-route
  annotations:
    konghq.com/preserve-host: 'false'
spec:
  parentRefs:
  - name: kong-gateway
    namespace: kong
  hostnames:
  - api.democluster.example
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: demoapi-svc
      kind: Service
      port: 8000
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: demoapi-mtls
spec:
  selector:
    matchLabels:
      app: demoapi
  mtls:
    mode: STRICT
