#
# A container that presents an X509 SVID as an OAuth client credential during OAuth grant requests
#
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y curl jq
CMD ["/bin/sleep", "infinity"]
