apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: orders-api-route
  annotations:
    konghq.com/plugins: phantom-token
spec:
  parentRefs:
  - name: kong-gateway
    namespace: kong
  hostnames:
  - api.democluster.example
  rules:
  - matches:
    - path:
        value: /orders
    backendRefs:
    - name: zerotrustapi-svc
      kind: Service
      port: 8000
