#
# An ingress into the OpenID Connect userinfo endpoint, using the BFF's hostname
# The ingress runs plugins that decrypt a cookie and deliver an opaque access token to the authorization server
#
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oauthuserinfo-web-route
  annotations:
    konghq.com/plugins: cors,oauth-proxy
spec:
  parentRefs:
  - name: kong-gateway
    namespace: kong
  hostnames:
  - api.webapp.example
  rules:
  - matches:
    - path:
        value: /oauthuserinfo
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /oauth/v2/oauth-userinfo
    backendRefs:
    - name: curity-idsvr-runtime-svc
      kind: Service
      port: 8443
