#
# An ingress route into the orders API, using the BFF's hostname
# The route runs plugins that decrypt a cookie and ultimately deliver a JWT access token to the API
#
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: orders-api-web-route
  annotations:
    konghq.com/plugins: cors,oauth-proxy,phantom-token
spec:
  parentRefs:
  - name: kong-gateway
    namespace: kong
  hostnames:
  - api.webapp.example
  rules:
  - matches:
    - path:
        value: /orders
    backendRefs:
    - name: zerotrustapi-svc
      kind: Service
      port: 8000
