#
# An ingress to enable routing to the OAuth Agent using the BFF host and a particular path
#
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oauth-agent-route
spec:
  parentRefs:
  - name: kong-gateway
    namespace: kong
  hostnames:
  - api.webapp.example
  rules:
  - matches:
    - path:
        value: /oauth-agent
    backendRefs:
    - name: oauth-agent-svc
      kind: Service
      port: 8000
